server:
  port: ${API_GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/v1/authentication/**

        - id: moex-data-service
          uri: lb://moex-data-service
          predicates:
            - Path=/v1/currencies/**
          filters:
            - AuthenticationFilter

authentication:
  base-url: http://localhost:${API_GATEWAY_PORT}/authentication
  token-endpoint: /token
  validate-token-endpoint: /validate-token
  register-endpoint: /register