server:
  port: 56783

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}
  instance:
    instance-id: ${random.uuid}

spring:
  application:
    name: quotation-data-aggregator-service

  kafka:
    bootstrap-servers: ${kafka:29092}

  cloud:
    openfeign:
      client:
        config:
          moex-client:
            url: https://iss.moex.com

kafka:
  retention: 14
  topic: "quotation.moex-data.currencies"

scheduler:
  currency-moex-client:
    cron-expression: "0 0 18 * * SUN"
    limit: 100
    securities:
      - "TRY"
      - "HKD"
      - "GBP"
      - "USD"
      - "EUR"
      - "CAD"
      - "CHF"
      - "KZT"
      - "JPY"
      - "CNY"
    meta-mode: "on"
    choice:
    string-order: